CREATE DATABASE BOOKSHOP;
GO

USE BOOKSHOP;

CREATE TABLE BOOKSHOP(
       ID int PRIMARY KEY,
	   Street varchar(255) NOT NULL,
	   Things varchar(255) NOT NULL
	   )


CREATE TABLE BOOKS(
       ID int PRIMARY KEY,
	   Name varchar(255) NOT NULL,
	   Cost int,
	   )


CREATE TABLE BOOK_NUMBERS(
       BOOKS_ID int NOT NULL,
	   BOOKSHOP_ID int NOT NULL,
	   FOREIGN KEY(BOOKS_ID) REFERENCES BOOKS(ID),
	   FOREIGN KEY(BOOKSHOP_ID) REFERENCES BOOKSHOP(ID)
	   )

CREATE TABLE CLIENTS(
     ID int PRIMARY KEY,
	 CASH int,
	 )

CREATE TABLE CLIENT_NUMBERS(
     CLIENTS_ID int NOT NULL,
	 BOOKSHOP_ID int NOT NULL,
	 FOREIGN KEY(CLIENTS_ID) REFERENCES CLIENTS(ID),
	 FOREIGN KEY(BOOKSHOP_ID) REFERENCES BOOKSHOP(ID)
	)

CREATE TABLE SWEETS(
      ID int PRIMARY KEY,
	  Name varchar(255) NOT NULL,
	  COST int
	  )

CREATE TABLE SWEET_NUMBERS(
      SWEETS_ID int NOT NULL,
	  BOOKSHOP_ID int NOT NULL,
	  FOREIGN KEY(SWEETS_ID) REFERENCES SWEETS(ID),
	  FOREIGN KEY(BOOKSHOP_ID) REFERENCES BOOKSHOP(ID)
	  )

CREATE TABLE SELLERS(
       ID int PRIMARY KEY,
	   CASH int,
	   ACHIEVEMENTS varchar(255) NOT NULL,
	   )

CREATE TABLE SELLER_NUMBERS(
        SELLERS_ID int NOT NULL,
		BOOKSHOP_ID int NOT NULL,
		FOREIGN KEY(SELLERS_ID) REFERENCES SELLERS(ID),
		FOREIGN KEY(BOOKSHOP_ID) REFERENCES BOOKSHOP(ID)
		)

CREATE TABLE ACHIEVEMENTS_SELLER(
        SELLERS_ID int NOT NULL,
		BOOKSHOP_ID int NOT NULL
		FOREIGN KEY(SELLERS_ID) REFERENCES SELLERS(ID),
		FOREIGN KEY(BOOKSHOP_ID) REFERENCES BOOKSHOP(ID)
		)







		INSERT INTO BOOKSHOP(ID,Street,Things)
		VALUES(1,'Tole BI','Sweets');

		INSERT INTO BOOKS(ID,Name,Cost)
		VALUES(4,'Garry Potter',2.000)

		INSERT INTO SELLERS(ID,CASH,ACHIEVEMENTS)
		VALUES(2,50.000,'The best Seller in this month')

		INSERT INTO SWEETS(ID,Name,COST)
		VALUES(11,'lollipop',4.000)




		INSERT INTO BOOKSHOP(ID,Street,Things)
		VALUES(2,'Kurmangazy','Books');

		INSERT INTO BOOKS(ID,Name,Cost)
		VALUES(5,'Love is Pain',1.000)

		INSERT INTO SELLERS(ID,CASH,ACHIEVEMENTS)
		VALUES(3,55.000,'Good worker')

		INSERT INTO SWEETS(ID,Name,COST)
		VALUES(12,'Bubble Gum',3.000)
		



		ALTER TABLE BOOKSHOP
		ADD CHECK (ID=1 AND Street='Tole BI' AND Things='Sweets')

        ALTER TABLE BOOKSHOP
		ADD CHECK (ID=2 AND Street='Kurmangazy' AND Things='Books')

		ALTER TABLE BOOKS
		ADD CHECK(ID=4 AND Name='Garry Potter' AND Cost=2.000)

		ALTER TABLE BOOKS
		ADD CHECK(ID=5 AND Name='Love Is Pain' AND Cost=1.000)

		ALTER TABLE SELLERS
		ADD CHECK(ID=2 AND CASH=50.000 AND ACHIEVEMENTS='The best Seller in this month')

		ALTER TABLE SELLERS
		ADD CHECK(ID=3 AND CASH=55.000 AND ACHIEVEMENTS='Good Worker')

		ALTER TABLE SWEETS
		ADD CHECK(ID=11 AND Name='lollipop' AND COST=4.000)


		ALTER TABLE SWEETS
		ADD CHECK(ID=12 AND Name='Bubble Gum' AND COST=3.000)


		ALTER TABLE BOOKSHOP
		ALTER COLUMN ID int NOT NULL;

		ALTER TABLE BOOKS
		ALTER COLUMN ID int NOT NULL;

		ALTER TABLE CLIENTS 
		ALTER COLUMN ID int NOT NULL;

		ALTER TABLE SELLERS
		ALTER COLUMN ID int NOT NULL;

		ALTER TABLE SWEETS
		ALTER COLUMN ID int NOT NULL;


		ALTER TABLE BOOKSHOP
		ADD UNIQUE (ID,Street)

		ALTER TABLE BOOKS
		ADD UNIQUE(ID,Name)

		ALTER TABLE CLIENTS
		ADD UNIQUE(ID)

		ALTER TABLE SELLERS
		ADD UNIQUE(ID,ACHIEVEMENTS)

		ALTER TABLE SWEETS
		ADD UNIQUE(ID,Name)
GO